version: "3"
services:
  web:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx:/etc/nginx/conf.d/
    networks:
      default:
        ipv4_address: 172.0.0.10
    depends_on:
      - php
    extra_hosts:
      - "host:172.0.0.1"
  php:
    #image: php:7.0-fpm
    build: ./dockerfile/php7.0-fpm/
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project
      - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ${PROJECT_PATH}:/www
    networks:
      default:
        ipv4_address: 172.0.0.20
    extra_hosts:
      - "host:172.0.0.10"
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    networks:
      default:
        ipv4_address: 172.0.0.30
    ports:
      - "3306:3306"
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      default:
        ipv4_address: 172.0.0.40
    ports:
      - "11211:11211"
networks:
  default:
    ipam:
      config:
        - subnet: 172.0.0.0/24