version: "3"
services:
  web:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./log/nginx:/var/log/nginx
      - ./conf/nginx:/etc/nginx/conf.d/
    networks:
      - webnet
    depends_on:
      - php
  php:
    #image: php:7.0-fpm
    build: ./dockerfile/php7.0-fpm/
    volumes:
      - ${PROJECT_PATH}:/var/www/html/project
    networks:
      - webnet
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd
    networks:
      - webnet
    ports:
      - "3307:3306"
  redis:
    image: "redis:alpine"
    restart: always
    networks:
      - webnet
networks:
  webnet: